
exports.WINSTON_DAILY_ROTATE_FILE_KEYS = [
  // A string representing the frequency of rotation. This is useful if you want to have timed rotations, as opposed to rotations that happen at specific moments in time. Valid values are '#m' or '#h' (e.g., '5m' or '3h'). Leaving this null relies on datePattern for the rotation times. (default: null)
  'frequency',

  // A string representing the moment.js date format to be used for rotating. The meta characters used in this string will dictate the frequency of the file rotation. For example, if your datePattern is simply 'HH' you will end up with 24 log files that are picked up and appended to every day. (default: 'YYYY-MM-DD')
  'datePattern',

  // A boolean to define whether or not to gzip archived log files. (default: 'false')
  'zippedArchive',

  // Filename to be used to log to. This filename can include the %DATE% placeholder which will include the formatted datePattern at that point in the filename. (default: 'winston.log.%DATE%')
  'filename',

  // The directory name to save log files to. (default: '.')
  'dirname',

  // Write directly to a custom stream and bypass the rotation capabilities. (default: null)
  'stream',

  // Maximum size of the file after which it will rotate. This can be a number of bytes, or units of kb, mb, and gb. If using the units, add 'k', 'm', or 'g' as the suffix. The units need to directly follow the number. (default: null)
  'maxSize',

  // Maximum number of logs to keep.
  // If not set, no logs will be removed.
  // This can be a number of files or number of days.
  // If using days, add 'd' as the suffix.
  // It uses auditFile to keep track of the log files in a json format.
  // It won't delete any file not contained in it.
  // It can be a number of files or number of days (default: null)
  'maxFiles',

  // An object resembling https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options indicating additional options that should be passed to the file stream. (default: { flags: 'a' })
  'options',

  // A string representing the name of the audit file. This can be used to override the default filename which is generated by computing a hash of the options object. (default: '..json')
  'auditFile',

  // Use UTC time for date in filename. (default: false)
  'utc',

  // File extension to be appended to the filename. (default: '')
  'extension',

  // Create a tailable symlink to the current active log file. (default: false)
  'createSymlink',

  // The name of the tailable symlink. (default: 'current.log')
  'symlinkName',

  // Use specified hashing algorithm for audit. (default: 'sha256')
  'auditHashType',

  // Name of the logging level that will be used for the transport, if not specified option from createLogger method will be used
  'level',
]
